# Generated by SnakeBridge v0.6.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: pylatexenc ~> 2.10

defmodule Pylatexenc do
  @moduledoc """
  SnakeBridge bindings for `pylatexenc`.
  """

  def __snakebridge_python_name__, do: "pylatexenc"
  def __snakebridge_library__, do: "pylatexenc"

  @doc false
  def __functions__ do
    []
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
