# Generated by SnakeBridge v0.6.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: sympy ~> 1.14

defmodule Sympy do
  @moduledoc """
  SnakeBridge bindings for `sympy`.
  """

  def __snakebridge_python_name__, do: "sympy"
  def __snakebridge_library__, do: "sympy"

  @doc false
  def __functions__ do
    []
  end

  @doc false
  def __classes__ do
    []
  end

  @doc false
  def __search__(query) do
    SnakeBridge.Docs.search(__MODULE__, query)
  end

  @doc false
  def doc(function) do
    SnakeBridge.Docs.get(__MODULE__, function)
  end
end
